server:
  port: 8080

spring:
  application:
    name: banking-app
  datasource:
    url: jdbc:h2:mem:bankingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true          # http://localhost:8080/h2-console
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

#PostgreSql Connection
#spring:
#  datasource:
#    url: jdbc:postgresql://<rds-endpoint>:5432/bankingdb
#    username: postgres
#    password: your-password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

# ─── Actuator ────────────────────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# ─── Logging ──────────────────────────────────────────────────────────────────
logging:
  level:
    root: INFO
    com.demo.banking: DEBUG
